# Model Configuration

# Backbone Configurations
camera_backbone:
  type: efficientnet
  pretrained: true
  channels:
    stage1: 32  # Early features (highest resolution)
    stage2: 64  # Mid-level features
    stage3: 128 # Higher-level features
    stage4: 256 # Deep features
    stage5: 512 # Final features

lidar_backbone:
  type: pointpillars
  voxel_size: [0.8, 0.8, 0.8]
  point_cloud_range: [-51.2, -51.2, -5, 51.2, 51.2, 3]
  max_num_points: 32
  max_voxels: 20000

# BEV Lifter Configuration
bev_lifter:
  bev_size: [128, 128]  # Match segmentation head output size
  bev_skip_channels:
    stage1: 32  # Early features (highest resolution)
    stage2: 64  # Mid-level features
    stage3: 128 # Deep features
  main_bev_channels: 128
  main_bev_source_stages: ['stage5']
  depth_channels: 64
  min_depth: 1.0
  max_depth: 60.0
  voxel_size: [0.4, 0.4]

# Fusion Configuration
fusion:
  type: cross_attention
  use_multi_scale: true  # Enable multi-scale fusion
  output_channels: 256  # Match with segmentation head input
  spatial_size: [128, 128]  # Match BEV size
  chunk_size: 1024
  use_reentrant: true
  stage_channels:
    stage1: 32
    stage2: 64
    stage3: 128

# Segmentation Head Configuration
segmentation_head:
  in_channels: 256  # Match fusion output channels
  skip_channels:
    stage1: 32  # Match BEV lifter skip channels
    stage2: 64
    stage3: 128
  decoder_channels: [128, 64, 32]  # Decoder channel progression
  num_classes: 6  # NuScenes BEV classes
  dropout: 0.1
  use_focal_loss: true
  focal_gamma: 2
  class_weights: [0.75, 0.5, 5.0, 5.0, 2.0, 1.0]  # Background, Road, Lane Divider, Road Divider, Walkway, Ped Crossing
  use_dice_loss: true
  dice_weight: 0.5
  dice_smooth: 1.0
  label_smoothing: 0.05
  output_size: [128, 128]  # Match BEV lifter output size

# Data Configuration
input_config:
  image_size: [640, 480]
  num_cameras: 1  # Using front camera only
  max_points_per_frame: 20000

# Class Mapping
class_map:
  background: 0
  drivable_area: 1
  lane_divider: 2
  road_divider: 3
  ped_crossing: 4
  walkway: 5

